name: Website Screenshot Update

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run the script
      run: node convertWebsiteToImage.js

    - name: Commit changes
      run: |
        git config --global user.name "ch1kim0n1"
        git config --global user.email "chikimoni61@gmail.com"
        git add -A
        git commit -m "new pic"
        git push
